-- SPDX-License-Identifier: MPL-2.0
||| Emits `src/generated/smtp_fsm.zig` from the proven protocol contracts:
||| the SMTP session tables (`Smtp.StateMachine`) and the NNTP ones
||| (`Nntp.StateMachine`), each with the golden vectors computed by its
||| serialization model.
|||
||| stdout is the artifact: `scripts/gen-fsm.sh` redirects it into the tree,
||| `scripts/check-fsm-drift.sh` regenerates and diffs in CI. The golden
||| vectors are EVALUATED here, by the spec's own functions — the Zig tests
||| then assert the Zig implementation agrees with the spec's answers.
|||
||| The module (and the package around it) keeps its `Smtp.` name although it
||| now emits both contracts: renaming it would touch the ipkg, both drift
||| scripts and this header in the same change that adds a second protocol,
||| and the drift gate is the one gate that must not go red for a naming
||| argument. The name is therefore a known wart, recorded rather than
||| hidden; it is a mechanical follow-up once the NNTP contract is green.
module Smtp.EmitZig

import Data.List  -- intersperse

import Smtp.StateMachine
import Smtp.Serialize
import Nntp.StateMachine
import Nntp.Serialize

%default total

phaseName : Phase -> String
phaseName PConnect  = "connect"
phaseName PEhlo     = "ehlo"
phaseName PStartTls = "starttls"
phaseName PEhloTls  = "ehlo_tls"
phaseName PAuth     = "auth"
phaseName PMailFrom = "mail_from"
phaseName PRcptTo   = "rcpt_to"
phaseName PData     = "data"
phaseName PPayload  = "payload"
phaseName PQuit     = "quit"
phaseName PDone     = "done"

actionName : Action -> String
actionName ANone      = "none"
actionName AEhlo      = "ehlo"
actionName AStartTls  = "starttls"
actionName AAuth      = "auth"
actionName AMailFrom  = "mail_from"
actionName ARcptTo    = "rcpt_to"
actionName AData      = "data"
actionName APayload   = "payload"
actionName AQuit      = "quit"

zigEscChar : Char -> String
zigEscChar '"'  = "\\\""
zigEscChar '\\' = "\\\\"
zigEscChar '\r' = "\\r"
zigEscChar '\n' = "\\n"
zigEscChar '\t' = "\\t"
zigEscChar c    =
  -- Any other control character as \xNN, so a corpus entry holding one
  -- still generates a valid Zig string literal.
  if ord c < 0x20 || ord c == 0x7f
     then "\\x" ++ pack [hexDigit (ord c `div` 16), hexDigit (ord c `mod` 16)]
     else pack [c]
  where
    hexDigit : Int -> Char
    hexDigit d = if d < 10 then chr (ord '0' + d) else chr (ord 'a' + d - 10)

zigEsc : List Char -> String
zigEsc cs = concat (map zigEscChar cs)

codeList : List Nat -> String
codeList cs = concat (intersperse ", " (map show cs))

stepLine : Step -> String
stepLine s =
  "    .{ .phase = ." ++ phaseName (phase s)
    ++ ", .send = ." ++ actionName (send s)
    ++ ", .expect = &.{ " ++ codeList (expect s) ++ " }"
    ++ ", .next = ." ++ phaseName (next s)
    ++ ", .repeats = " ++ (if repeats s then "true" else "false")
    ++ " },"

stuffVectorLine : List Char -> String
stuffVectorLine cs =
  "    .{ .input = \"" ++ zigEsc cs
    ++ "\", .expected = \"" ++ zigEsc (stuffLine cs) ++ "\" },"

headerVectorLine : List Char -> String
headerVectorLine cs =
  "    .{ .input = \"" ++ zigEsc cs
    ++ "\", .ok = " ++ (if headerValueOk cs then "true" else "false") ++ " },"

langVectorLine : List Char -> String
langVectorLine cs =
  "    .{ .input = \"" ++ zigEsc cs
    ++ "\", .ok = " ++ (if contentLanguageOk cs then "true" else "false") ++ " },"

nntpPhaseName : NPhase -> String
nntpPhaseName NConnect      = "connect"
nntpPhaseName NCapabilities = "capabilities"
nntpPhaseName NStartTls     = "starttls"
nntpPhaseName NCapsTls      = "caps_tls"
nntpPhaseName NAuth         = "auth"
nntpPhaseName NPost         = "post"
nntpPhaseName NPayload      = "payload"
nntpPhaseName NQuit         = "quit"
nntpPhaseName NDone         = "done"

nntpActionName : NAction -> String
nntpActionName NActNone         = "none"
nntpActionName NActCapabilities = "capabilities"
nntpActionName NActStartTls     = "starttls"
nntpActionName NActAuthInfo     = "authinfo"
nntpActionName NActPost         = "post"
nntpActionName NActPayload      = "payload"
nntpActionName NActQuit         = "quit"

nntpStepLine : NStep -> String
nntpStepLine s =
  "    .{ .nphase = ." ++ nntpPhaseName (nphase s)
    ++ ", .nsend = ." ++ nntpActionName (nsend s)
    ++ ", .nexpect = &.{ " ++ codeList (nexpect s) ++ " }"
    ++ ", .nnext = ." ++ nntpPhaseName (nnext s)
    ++ ", .nrepeats = " ++ (if nrepeats s then "true" else "false")
    ++ " },"

newsgroupVectorLine : List Char -> String
newsgroupVectorLine cs =
  "    .{ .input = \"" ++ zigEsc cs
    ++ "\", .ok = " ++ (if newsgroupsOk cs then "true" else "false") ++ " },"

output : List String
output =
  [ "// GENERATED by spec/Smtp/EmitZig.idr from the proven protocol contract."
  , "// DO NOT EDIT — run scripts/gen-fsm.sh; CI diffs this file against a"
  , "// fresh generation and fails on drift."
  , "// SPDX-License-Identifier: MPL-2.0"
  , "//"
  , "// Carries both proven session contracts — SMTP (RFC 5321, RFC 3207) and"
  , "// NNTP (RFC 3977, RFC 4642) — plus the message-grammar golden vectors"
  , "// each one is checked against. The SMTP tables are unchanged from"
  , "// v0.4.0; the `nntp_*` section is additive."
  , ""
  , "pub const Phase = enum(u8) { connect, ehlo, starttls, ehlo_tls, auth, mail_from, rcpt_to, data, payload, quit, done };"
  , ""
  , "pub const Action = enum(u8) { none, ehlo, starttls, auth, mail_from, rcpt_to, data, payload, quit };"
  , ""
  , "pub const Step = struct {"
  , "    phase: Phase,"
  , "    send: Action,"
  , "    /// Reply codes accepted as success. 4xx = transient failure,"
  , "    /// 5xx = permanent failure, anything else = protocol error."
  , "    expect: []const u16,"
  , "    next: Phase,"
  , "    /// RCPT TO re-runs this row per recipient before advancing."
  , "    repeats: bool,"
  , "};"
  , ""
  , "/// Session over an already-encrypted or deliberately plain stream."
  , "/// These rows are the contract that shipped in v0.2.0."
  , "pub const script_implicit = [_]Step{"
  ]
  ++ map stepLine scriptImplicit
  ++
  [ "};"
  , ""
  , "/// Session that begins in cleartext on the submission port and"
  , "/// upgrades in place (RFC 3207). The second EHLO is mandatory: the"
  , "/// server may advertise differently once the session is encrypted."
  , "pub const script_starttls = [_]Step{"
  ]
  ++ map stepLine scriptStartTls
  ++
  [ "};"
  , ""
  , "/// The table for a transport. Selecting by value rather than exporting"
  , "/// one `script` keeps the caller from silently walking the wrong shape."
  , "pub fn scriptFor(starttls: bool) []const Step {"
  , "    return if (starttls) &script_starttls else &script_implicit;"
  , "}"
  , ""
  , "pub const StuffVector = struct { input: []const u8, expected: []const u8 };"
  , ""
  , "/// (input line, transmit encoding) pairs computed by Smtp.Serialize.stuffLine."
  , "pub const stuff_vectors = [_]StuffVector{"
  ]
  ++ map stuffVectorLine stuffCorpus
  ++
  [ "};"
  , ""
  , "pub const HeaderVector = struct { input: []const u8, ok: bool };"
  , ""
  , "/// Header-injection verdicts computed by Smtp.Serialize.headerValueOk."
  , "pub const header_vectors = [_]HeaderVector{"
  ]
  ++ map headerVectorLine headerCorpus
  ++
  [ "};"
  , ""
  , "/// Content-Language verdicts computed by Smtp.Serialize.contentLanguageOk"
  , "/// (RFC 3282 list of RFC 5646 tags, well-formedness only)."
  , "pub const lang_vectors = [_]HeaderVector{"
  ]
  ++ map langVectorLine langCorpus
  ++
  [ "};"
  , ""
  , "// ---------------------------------------------------------------------------"
  , "// NNTP (RFC 3977): posting one article. Separate enums rather than shared"
  , "// ones, because the reply that matters most is the greeting: 201 is a"
  , "// SUCCESSFUL greeting that forbids exactly what this client came to do,"
  , "// and 101, 340 and 382 are intermediate replies that are not one class."
  , "// An SMTP-shaped enum would be a lie in the type."
  , ""
  , "pub const NPhase = enum(u8) { connect, capabilities, starttls, caps_tls, auth, post, payload, quit, done };"
  , ""
  , "pub const NAction = enum(u8) { none, capabilities, starttls, authinfo, post, payload, quit };"
  , ""
  , "pub const NStep = struct {"
  , "    nphase: NPhase,"
  , "    nsend: NAction,"
  , "    /// Reply codes accepted as success. 4xx = transient failure,"
  , "    /// 5xx = permanent failure, anything else = protocol error."
  , "    nexpect: []const u16,"
  , "    nnext: NPhase,"
  , "    /// Always false: one article per session. A field rather than an"
  , "    /// omission, so a repeating row would fail the spec's nNoRepeats"
  , "    /// instead of silently disagreeing with the driver."
  , "    nrepeats: bool,"
  , "};"
  , ""
  , "/// Session over an already-encrypted (NNTPS, port 563) or deliberately"
  , "/// plain stream. One article per session."
  , "pub const nntp_script_implicit = [_]NStep{"
  ]
  ++ map nntpStepLine nScriptImplicit
  ++
  [ "};"
  , ""
  , "/// Session that begins in cleartext on the news port and upgrades in"
  , "/// place (RFC 4642). The second CAPABILITIES is mandatory: the server"
  , "/// may advertise differently once the session is encrypted."
  , "pub const nntp_script_starttls = [_]NStep{"
  ]
  ++ map nntpStepLine nScriptStartTls
  ++
  [ "};"
  , ""
  , "/// The table for a transport. Selecting by value rather than exporting"
  , "/// one `script` keeps the caller from silently walking the wrong shape."
  , "pub fn nntpScriptFor(starttls: bool) []const NStep {"
  , "    return if (starttls) &nntp_script_starttls else &nntp_script_implicit;"
  , "}"
  , ""
  , "pub const NewsgroupVector = struct { input: []const u8, ok: bool };"
  , ""
  , "/// Newsgroups verdicts computed by Nntp.Serialize.newsgroupsOk"
  , "/// (RFC 5536 name list, well-formedness only; `control` refused)."
  , "pub const newsgroup_vectors = [_]NewsgroupVector{"
  ]
  ++ map newsgroupVectorLine newsgroupCorpus
  ++
  [ "};"
  ]

main : IO ()
main = putStr (concat (map (++ "\n") output))
