-- SPDX-License-Identifier: MPL-2.0
||| Emits `src/generated/smtp_fsm.zig` from the proven protocol contract.
|||
||| stdout is the artifact: `scripts/gen-fsm.sh` redirects it into the tree,
||| `scripts/check-fsm-drift.sh` regenerates and diffs in CI. The golden
||| vectors are EVALUATED here, by the spec's own functions — the Zig tests
||| then assert the Zig implementation agrees with the spec's answers.
module Smtp.EmitZig

import Data.List  -- intersperse

import Smtp.StateMachine
import Smtp.Serialize

%default total

phaseName : Phase -> String
phaseName PConnect  = "connect"
phaseName PEhlo     = "ehlo"
phaseName PAuth     = "auth"
phaseName PMailFrom = "mail_from"
phaseName PRcptTo   = "rcpt_to"
phaseName PData     = "data"
phaseName PPayload  = "payload"
phaseName PQuit     = "quit"
phaseName PDone     = "done"

actionName : Action -> String
actionName ANone      = "none"
actionName AEhlo      = "ehlo"
actionName AAuthPlain = "auth_plain"
actionName AMailFrom  = "mail_from"
actionName ARcptTo    = "rcpt_to"
actionName AData      = "data"
actionName APayload   = "payload"
actionName AQuit      = "quit"

zigEscChar : Char -> String
zigEscChar '"'  = "\\\""
zigEscChar '\\' = "\\\\"
zigEscChar '\r' = "\\r"
zigEscChar '\n' = "\\n"
zigEscChar c    = pack [c]

zigEsc : List Char -> String
zigEsc cs = concat (map zigEscChar cs)

codeList : List Nat -> String
codeList cs = concat (intersperse ", " (map show cs))

stepLine : Step -> String
stepLine s =
  "    .{ .phase = ." ++ phaseName (phase s)
    ++ ", .send = ." ++ actionName (send s)
    ++ ", .expect = &.{ " ++ codeList (expect s) ++ " }"
    ++ ", .next = ." ++ phaseName (next s)
    ++ ", .repeats = " ++ (if repeats s then "true" else "false")
    ++ " },"

stuffVectorLine : List Char -> String
stuffVectorLine cs =
  "    .{ .input = \"" ++ zigEsc cs
    ++ "\", .expected = \"" ++ zigEsc (stuffLine cs) ++ "\" },"

headerVectorLine : List Char -> String
headerVectorLine cs =
  "    .{ .input = \"" ++ zigEsc cs
    ++ "\", .ok = " ++ (if headerValueOk cs then "true" else "false") ++ " },"

output : List String
output =
  [ "// GENERATED by spec/Smtp/EmitZig.idr from the proven protocol contract."
  , "// DO NOT EDIT — run scripts/gen-fsm.sh; CI diffs this file against a"
  , "// fresh generation and fails on drift."
  , "// SPDX-License-Identifier: MPL-2.0"
  , ""
  , "pub const Phase = enum(u8) { connect, ehlo, auth, mail_from, rcpt_to, data, payload, quit, done };"
  , ""
  , "pub const Action = enum(u8) { none, ehlo, auth_plain, mail_from, rcpt_to, data, payload, quit };"
  , ""
  , "pub const Step = struct {"
  , "    phase: Phase,"
  , "    send: Action,"
  , "    /// Reply codes accepted as success. 4xx = transient failure,"
  , "    /// 5xx = permanent failure, anything else = protocol error."
  , "    expect: []const u16,"
  , "    next: Phase,"
  , "    /// RCPT TO re-runs this row per recipient before advancing."
  , "    repeats: bool,"
  , "};"
  , ""
  , "pub const script = [_]Step{"
  ]
  ++ map stepLine script
  ++
  [ "};"
  , ""
  , "pub const StuffVector = struct { input: []const u8, expected: []const u8 };"
  , ""
  , "/// (input line, transmit encoding) pairs computed by Smtp.Serialize.stuffLine."
  , "pub const stuff_vectors = [_]StuffVector{"
  ]
  ++ map stuffVectorLine stuffCorpus
  ++
  [ "};"
  , ""
  , "pub const HeaderVector = struct { input: []const u8, ok: bool };"
  , ""
  , "/// Header-injection verdicts computed by Smtp.Serialize.headerValueOk."
  , "pub const header_vectors = [_]HeaderVector{"
  ]
  ++ map headerVectorLine headerCorpus
  ++
  [ "};"
  ]

main : IO ()
main = putStr (concat (map (++ "\n") output))
